# Generated by Django 4.1.3 on 2022-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soniablog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
